### ISSUE TITLE
cart.component.html

### ISSUE THREAD

**Issue by VZhyrytskiy** [Roksolana27/AngularShop#2]
Немного сложновато читаются большие темплейты, даже с комментариями.
Вы теперь знаете как коммуницировать между компонентами, 
может быть захотите темплейты разбить на отдельные компоненты для простоты.

**Comment by Roksolana27** [comment]
Да, согласна. Корзину уже разбила на два компонента, для комуникации использовала Input, EventEmitter и Output. Надеюсь все сделала правильно
